export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST';
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE';

export const FIND_PRODUCT_BY_REQUEST = "FIND_PRODUCT_CATEGORY_REQUEST";
export const FIND_PRODUCT_BY_SUCCESS = "FIND_PRODUCT_CATEGORY_SUCCESS";
export const FIND_PRODUCT_BY_FAILURE = "FIND_PRODUCT_CATEGORY_FAILURE";
